using System.IO;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Xml;
using System.Xml.Linq;

namespace SharePointSmartCopy.Services;

public enum OpcCompareResult { VolatileOnlyDifferences, ContentMismatch, NotComparable }

// DifferingParts: up to a handful of content-part paths that actually differed (or were missing
// on one side), for the report's Note column. Empty for VolatileOnlyDifferences/NotComparable.
public sealed record OpcCompareOutcome(OpcCompareResult Result, IReadOnlyList<string> DifferingParts);

// Compares two Office Open XML (OOXML) packages — .docx/.xlsx/.pptx and their macro-enabled/
// template/add-in variants — at the content-part level, ignoring the parts SharePoint rewrites
// independently of content (document property promotion/demotion, Document ID stamping,
// sensitivity-label metadata). Pure and side-effect-free: takes two seekable streams, returns a
// verdict. See SharePointSmartCopy/Docs/DEEP-VERIFY-PLAN.md for the full design rationale.
//
// XML parts are compared STRUCTURALLY (parsed + XNode.DeepEquals), not by raw byte hash. A raw
// byte comparison is too strict for OOXML: attribute order, namespace-prefix spelling, and
// insignificant whitespace can all legitimately differ between two otherwise-identical saves, and
// Word's per-save "rsid" markers (see StripRevisionSaveIds) are regenerated on every save whether
// or not visible content changed. All of these produced false ContentMismatch results under a
// pure byte-hash comparison. Binary parts (media, etc.) still use a byte hash — there's no
// structural representation to normalize.
public static class OpcDeepComparer
{
    // Parts SharePoint rewrites independently of content — excluded from comparison entirely.
    // Prefix match, case-insensitive, forward-slash-normalized paths.
    private static readonly string[] VolatilePrefixes =
    {
        "docProps/",   // core.xml (Modified/ModifiedBy), app.xml, custom.xml (Document ID, ContentTypeId)
        "customXml/",  // custom XML parts SharePoint adds/rewrites (Document ID item parts, etc.)
        "[trash]/",    // SharePoint's own non-conformant deleted-entry area (observed in the wild)
    };

    // Exact-path volatile entries.
    private static readonly string[] VolatileExact =
    {
        "_rels/.rels",          // relationship ids/order shift when docProps parts are added
        "[Content_Types].xml",  // gains Override entries for any added parts
        // Excel's calculation-dependency-order cache. Regenerated by Excel on every save, often in
        // a different order, and has NO effect on calculated values (those are cached separately
        // in each sheet's own XML) — a reordered calcChain is never a real content difference.
        "xl/calcChain.xml",
    };

    private static readonly XNamespace RelsNs = "http://schemas.openxmlformats.org/package/2006/relationships";

    public static OpcCompareOutcome Compare(Stream source, Stream target)
    {
        Dictionary<string, PartContent> sourceParts;
        Dictionary<string, PartContent> targetParts;
        try
        {
            sourceParts = ReadParts(source);
        }
        catch (InvalidDataException)
        {
            return new OpcCompareOutcome(OpcCompareResult.NotComparable, []);
        }
        try
        {
            targetParts = ReadParts(target);
        }
        catch (InvalidDataException)
        {
            return new OpcCompareOutcome(OpcCompareResult.NotComparable, []);
        }

        var differing = new List<string>();
        foreach (var (path, sourcePart) in sourceParts)
        {
            if (!targetParts.TryGetValue(path, out var targetPart))
            {
                differing.Add(path);
                continue;
            }
            if (!PartsEqual(path, sourcePart, targetPart, out var detail))
                differing.Add(detail != null ? $"{path} [{detail}]" : path);
        }
        foreach (var path in targetParts.Keys)
        {
            if (!sourceParts.ContainsKey(path))
                differing.Add(path);
        }

        if (differing.Count == 0)
            return new OpcCompareOutcome(OpcCompareResult.VolatileOnlyDifferences, []);

        // Cap the reported list — the report just needs enough to be actionable, not an exhaustive
        // diff. Deduplicate first: the two loops above can't produce the same path twice, but a
        // defensive Distinct costs nothing here.
        return new OpcCompareOutcome(OpcCompareResult.ContentMismatch,
            differing.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(p => p, StringComparer.OrdinalIgnoreCase).Take(5).ToList());
    }

    // XML parts keep their raw bytes (parsed lazily, per comparison, so a part that turns out to
    // be volatile-adjacent noise never pays parse cost it doesn't need). Binary parts keep only a
    // hash — buffering large media fully just to hash it once is wasted memory.
    private sealed record PartContent(bool IsXml, byte[]? XmlBytes, byte[]? BinaryHash);

    // Throws InvalidDataException (via ZipArchive) when the stream isn't a valid ZIP — covers
    // label-encrypted files, which aren't ZIPs at all, and any other corrupt/unexpected content.
    private static Dictionary<string, PartContent> ReadParts(Stream stream)
    {
        var result = new Dictionary<string, PartContent>(StringComparer.OrdinalIgnoreCase);
        using var archive = new ZipArchive(stream, ZipArchiveMode.Read, leaveOpen: true);
        foreach (var entry in archive.Entries)
        {
            var normalized = entry.FullName.Replace('\\', '/');
            if (normalized.Length == 0 || normalized.EndsWith('/')) continue; // directory entry
            if (IsVolatile(normalized)) continue;

            using var entryStream = entry.Open();
            if (IsXmlPart(normalized))
            {
                using var buffer = new MemoryStream();
                entryStream.CopyTo(buffer);
                result[normalized] = new PartContent(true, buffer.ToArray(), null);
            }
            else
            {
                // Stream straight through — embedded media inside a content part (images, video)
                // can be large; no need to buffer it just to hash it.
                result[normalized] = new PartContent(false, null, SHA256.HashData(entryStream));
            }
        }
        return result;
    }

    // .vml (legacy Vector Markup Language, used for comments/form-control drawings in .xlsx) is
    // plain XML despite the non-".xml" extension. Without this, .vml parts fell through to the
    // binary byte-hash path below — far stricter than every other XML part in the package, so
    // insignificant whitespace/attribute-order differences from a resave were reported as a hard
    // ContentMismatch instead of being structurally compared like everything else.
    private static bool IsXmlPart(string normalizedPath) =>
        normalizedPath.EndsWith(".xml", StringComparison.OrdinalIgnoreCase) ||
        normalizedPath.EndsWith(".rels", StringComparison.OrdinalIgnoreCase) ||
        normalizedPath.EndsWith(".vml", StringComparison.OrdinalIgnoreCase);

    // detail is populated only for a .rels mismatch — the actual differing relationship entries,
    // so a future false positive shows up in the report instead of requiring another guess-a-cause
    // round (this exact part has now produced three separate false-positive theories in a row;
    // if there's a fourth, this is what will actually reveal it instead of more speculation).
    private static bool PartsEqual(string path, PartContent a, PartContent b, out string? detail)
    {
        detail = null;
        if (!a.IsXml)
            return a.BinaryHash!.AsSpan().SequenceEqual(b.BinaryHash!);

        if (TryNormalizeXml(a.XmlBytes!, out var docA) && TryNormalizeXml(b.XmlBytes!, out var docB))
        {
            if (path.EndsWith(".rels", StringComparison.OrdinalIgnoreCase))
                return RelationshipSetsEqual(GetOwnerDirectory(path), docA!, docB!, out detail);
            return XNode.DeepEquals(docA, docB);
        }

        // Not well-formed XML despite the extension (rare) — fall back to raw byte equality
        // rather than silently treating an unparsable part as a match.
        return a.XmlBytes!.AsSpan().SequenceEqual(b.XmlBytes);
    }

    // .rels parts list a package's relationships (Id -> Type/Target/TargetMode). The Id values and
    // their ordering are writer-assigned implementation details, not content — Excel and SharePoint
    // can renumber or reorder them across saves with zero actual change. Compared as an
    // order-independent set of (Type, Target, TargetMode).
    //
    // A relationship whose Target resolves to a part we ALREADY treat as volatile (customXml/*,
    // xl/calcChain.xml, etc. — see IsVolatile) is filtered out entirely rather than compared. Two
    // separate real cases proved that excluding a volatile PART's own content isn't enough on its
    // own: Excel adds/removes the calcChain relationship on a one-sided recalculation, and
    // SharePoint adds a customXml relationship when it stamps a Document ID part — both are
    // genuine structural changes to the .rels XML even though they only ever point at content we
    // already ignore. Filtering by resolved target (not a hardcoded list of relationship Type
    // URIs) means any FUTURE relationship pointing into an already-volatile part is caught the
    // same way, without needing another whack-a-mole fix each time a new one turns up.
    private static bool RelationshipSetsEqual(string ownerDir, XDocument a, XDocument b, out string? detail)
    {
        var setA = RelationshipSet(ownerDir, a);
        var setB = RelationshipSet(ownerDir, b);
        if (setA.SetEquals(setB)) { detail = null; return true; }

        var onlyInSource = setA.Except(setB).Take(3).ToList();
        var onlyInTarget = setB.Except(setA).Take(3).ToList();
        var parts = new List<string>();
        if (onlyInSource.Count > 0) parts.Add($"only in source: {string.Join("; ", onlyInSource)}");
        if (onlyInTarget.Count > 0) parts.Add($"only in target: {string.Join("; ", onlyInTarget)}");
        detail = string.Join(" | ", parts);
        return false;
    }

    private static HashSet<string> RelationshipSet(string ownerDir, XDocument doc) =>
        doc.Root?
            .Elements(RelsNs + "Relationship")
            .Where(r =>
            {
                // External targets (URLs, UNC paths, etc.) aren't part paths at all — nothing to
                // resolve, and they can't point at a part we've excluded.
                var mode = (string?)r.Attribute("TargetMode") ?? "Internal";
                if (!string.Equals(mode, "Internal", StringComparison.OrdinalIgnoreCase)) return true;
                var target = (string?)r.Attribute("Target");
                return target == null || !IsVolatile(ResolveRelativeTarget(ownerDir, target));
            })
            // TargetMode is OPTIONAL per the OOXML spec and defaults to "Internal" when omitted —
            // a source .rels that omits it and a re-saved target .rels that writes it out
            // explicitly are semantically identical, but building the tuple from the raw (possibly
            // null) attribute value treated that as two different relationships.
            .Select(r => $"{(string?)r.Attribute("Type")}|{(string?)r.Attribute("Target")}|{(string?)r.Attribute("TargetMode") ?? "Internal"}")
            .ToHashSet(StringComparer.Ordinal)
        ?? new HashSet<string>();

    // A .rels part always lives at "{dir}/_rels/{partFileName}.rels", describing relationships FROM
    // the part at "{dir}/{partFileName}" — e.g. "xl/_rels/workbook.xml.rels" describes
    // relationships from "xl/workbook.xml", so relative Targets inside it resolve against "xl".
    private static string GetOwnerDirectory(string relsPath)
    {
        var idx = relsPath.LastIndexOf("/_rels/", StringComparison.OrdinalIgnoreCase);
        return idx < 0 ? "" : relsPath[..idx];
    }

    // Resolves a relationship Target (which may include "../" segments) against the owning part's
    // directory into a normalized package-relative path, the same shape IsVolatile expects.
    private static string ResolveRelativeTarget(string ownerDir, string target)
    {
        var combined = string.IsNullOrEmpty(ownerDir) ? target : $"{ownerDir}/{target}";
        var segments = new List<string>();
        foreach (var seg in combined.Replace('\\', '/').Split('/'))
        {
            if (seg == "..") { if (segments.Count > 0) segments.RemoveAt(segments.Count - 1); }
            else if (seg.Length == 0 || seg == ".") { /* skip */ }
            else segments.Add(seg);
        }
        return string.Join("/", segments);
    }

    private static bool TryNormalizeXml(byte[] xmlBytes, out XDocument? doc)
    {
        try
        {
            using var ms = new MemoryStream(xmlBytes);
            // LoadOptions.None (the default): discards insignificant inter-element whitespace
            // while preserving significant whitespace inside text content (e.g. <w:t xml:space=
            // "preserve">) — exactly the distinction OOXML itself makes.
            doc = XDocument.Load(ms);
            StripRevisionSaveIds(doc.Root);
            StripCalcId(doc.Root);
            StripViewState(doc.Root);
            return true;
        }
        catch (XmlException)
        {
            doc = null;
            return false;
        }
    }

    // Strips Word's per-save "revision save ID" (rsid) markers. Word regenerates these on every
    // save — including a silent save triggered by SharePoint's own preview/co-authoring pipeline
    // opening the file — regardless of whether any visible content changed, so they're pure
    // save-session noise rather than content. Covers both forms they appear in:
    //   - Attributes scattered through word/document.xml: w:rsid, w:rsidR, w:rsidRPr,
    //     w:rsidRDefault, w:rsidP, w:rsidTr, w:rsidSect, w:rsidDel, w:rsidTbl, ...
    //   - The <w:rsids> block in word/settings.xml: a full list of every rsid used in the
    //     document, regenerated wholesale on every save.
    // No-op for Excel/PowerPoint XML, which doesn't use this namespace/naming convention.
    private static void StripRevisionSaveIds(XElement? root)
    {
        if (root == null) return;
        foreach (var el in root.DescendantsAndSelf().ToList())
        {
            foreach (var attr in el.Attributes()
                         .Where(a => a.Name.LocalName.StartsWith("rsid", StringComparison.OrdinalIgnoreCase))
                         .ToList())
                attr.Remove();

            if (el.Name.LocalName.Equals("rsid", StringComparison.OrdinalIgnoreCase) ||
                el.Name.LocalName.Equals("rsids", StringComparison.OrdinalIgnoreCase))
                el.Remove();
        }
    }

    // <bookViews> (xl/workbook.xml) and <sheetViews> (xl/worksheets/sheetN.xml) store pure
    // window/UI state as of the last save — window position and size, which sheet tab was active,
    // which cell was selected, zoom level — none of it calculated content. Whatever process last
    // touched the file (a different machine's screen resolution, SharePoint's own backend preview/
    // indexing pipeline opening it) regenerates these with no effect on any actual value, producing
    // a structural diff in workbook.xml and/or individual worksheet XML that looks like real content
    // changed when nothing did. No-op for Word/PowerPoint XML, which has no such elements.
    private static void StripViewState(XElement? root)
    {
        if (root == null) return;
        foreach (var el in root.DescendantsAndSelf()
                     .Where(e => e.Name.LocalName == "bookViews" || e.Name.LocalName == "sheetViews")
                     .ToList())
            el.Remove();
    }

    // Excel bumps xl/workbook.xml's <calcPr calcId="..."/> on every recalculation — including one
    // silently triggered by SharePoint's own preview/co-authoring pipeline opening the file — the
    // same class of save-session noise as xl/calcChain.xml, just living inside workbook.xml itself
    // rather than a relationship. calcId has no effect on
    // any calculated value; fullCalcOnLoad merely tells Excel whether to recalculate on next open,
    // also not a content difference. No-op for Word/PowerPoint XML, which has no calcPr element.
    private static void StripCalcId(XElement? root)
    {
        if (root == null) return;
        foreach (var calcPr in root.DescendantsAndSelf().Where(el => el.Name.LocalName == "calcPr"))
        {
            calcPr.Attribute("calcId")?.Remove();
            calcPr.Attribute("fullCalcOnLoad")?.Remove();
        }
    }

    private static bool IsVolatile(string normalizedPath)
    {
        foreach (var exact in VolatileExact)
            if (string.Equals(normalizedPath, exact, StringComparison.OrdinalIgnoreCase))
                return true;
        foreach (var prefix in VolatilePrefixes)
            if (normalizedPath.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                return true;
        return false;
    }
}
